### PR TITLE
Use meson for building

### LINKED ISSUE #72: Provide a pkg-config file
It'd be nice if it was possible to build a dynamic lib of hunt and discover it via pkg-config

### PR DESCRIPTION
**Pull request by Cogitri**
This is still very WIP. This is still missing:

* ~Handling of docs, resources and examples~

* ~Properly handling HAVE_EPOLL and friends~

* ~Proper linking of the shared libs which depend on each other (I think right now ldc just pulls in the right files so we end up with duplication)~

* Fix conflicting constructors/destructors

fixes #72

### CODE REVIEW

**Comment by Cogitri** [comment]
Ah, I guess it won't be possible to split hunt into multiple libs due to it being so interconnected... I guess I'll just have to make one (rather) massive lib, although I don't really like that too much.

**Comment by Cogitri** [comment]
Hm, I'm currently getting the following when running an exe linking to hunt:

```
object.Error@rt/minfo.d(371): Cyclic dependency between module constructors/destructors of hunt.concurrency.Executors and hunt.concurrency.AbstractExecutorService
hunt.concurrency.Executors* ->
hunt.concurrency.AbstractExecutorService* ->
hunt.concurrency.FutureTask* ->
hunt.concurrency.Executors*

Illegal instruction (core dumped)
```

**Comment by Cogitri** [comment]
Hm, I think the stuff in resources/ is included on runtime, not sure how that is supposed to work unless you run the command in the root of the hunt repo :thinking:

**Comment by Cogitri** [comment]
The examples work now if you pass `--DRT-oncycle=ignore` to  the binaries due to the dep cycle mentioned above.

**Comment by Heromyth** [comment]
> 
> 
> Ah, I guess it won't be possible to split hunt into multiple libs due to it being so interconnected... I guess I'll just have to make one (rather) massive lib, although I don't really like that too much.

It will not be done in a short time, but it will in a long time.

**Comment by Heromyth** [comment]
> 
> 
> Hm, I'm currently getting the following when running an exe linking to hunt:
> 
> ```
> object.Error@rt/minfo.d(371): Cyclic dependency between module constructors/destructors of hunt.concurrency.Executors and hunt.concurrency.AbstractExecutorService
> hunt.concurrency.Executors* ->
> hunt.concurrency.AbstractExecutorService* ->
> hunt.concurrency.FutureTask* ->
> hunt.concurrency.Executors*
> 
> Illegal instruction (core dumped)
> ```

It makes me headache! Running `dub test` can't detect this. So, we will try to fix this in near future.

**Comment by Heromyth** [comment]
> 
> 
> Hm, I think the stuff in resources/ is included on runtime, not sure how that is supposed to work unless you run the command in the root of the hunt repo 🤔

The whole resources directory should be copied into the root in your project. They are used by hunt.util.MimeTypeUtils and hunt.util.Locale respectively

**Comment by Heromyth** [comment]
The main problem for Meson is that it can't include all the source files in a directory automatically, especially for a unstable project.

**Comment by Cogitri** [comment]
> It makes me headache! Running dub test can't detect this. So, we will try to fix this in near future.

Thanks. No clue why it only happens with meson and not with dub.

> The whole resources directory should be copied into the root in your project. They are used by hunt.util.MimeTypeUtils and hunt.util.Locale respectively

Hm, in my opinion we shouldn't have projects copy those into the root of their projects but instead have a shared copy of these somewhere in the system. I'll see what I can do.

> The main problem for Meson is that it can't include all the source files in a directory automatically, especially for a unstable project.

I personally don't see the problem with adding/removing a file when you're adding/removing a line. We could emulate scanning for sources in meson, but that's rather fragile.

**Comment by Cogitri** [comment]
> Thanks. No clue why it only happens with meson and not with dub.

Ah! Apparently this only happens when building with meson in debug mode (i.e. with `--buildtype=debug`, which is also the default of meson). It works fine if you do `meson --buildtype=release` and build that then.

**Comment by Cogitri** [comment]
Ah, it's due to meson adding `-d-debug` to LDC's arguments.

**Comment by Cogitri** [comment]
I've started to use this in a project of mine and it appears to work fine.

**Comment by Heromyth** [comment]
Thanks for your great works! Notify us please after you finished this patch.

**Comment by Cogitri** [comment]
Seems to work now :tada:

**Comment by Heromyth** [comment]
Great works! We will merge it soon.

**Comment by Heromyth** [comment]
I run `ninja -C build test` and got this error:
```unrecognized switch '-link-defaultlib-shared'```

It seems that dmd can't recongnize this option `-link-defaultlib-shared`

**Comment by Cogitri** [comment]
Oh, I guess the option differs between dmd and ldc. I'll look into it

-------- Original Message --------

**Pull request merged**
